version: "3.9"

services:
  coding-chain-api:
    container_name: coding-chain-api
    image: coding-chain/api
    build:
      context: ../coding-chain-api
    restart: unless-stopped
    ports:
      - 5002:5002
      - 5003:5003
    environment:
      ASPNETCORE_URLS: https://+:5003;http://+:5002
      ASPNETCORE_ENVIRONMENT: Development
      ASPNECORE_DatabaseSettings_ConnectionString: "Server=coding-chain-db;Database=coding_chain;User Id=sa;Password=codingDevPwd21;"
      ASPNETCORE_Kestrel__Certificates__Default__Password: codingchainapi
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/CodingChainApi.WebApi.pfx
    volumes:
      -  /home/sbailleul/.aspnet/https/:/https
      -  ./coding-chain-api:/app/AppData

  coding-chain-db:
    container_name: coding-chain-db
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=codingDevPwd21
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - ./database:/var/opt/mssql/data
  rabbitmq:
    image: rabbitmq:3-management
    hostname: my-rabbit
    ports:
      - 5672:5672
      - 15672:15672

