version: "3.9"

services:
  ## APPLICATIONS ##
  coding-chain-api:
    container_name: coding-chain-api
    depends_on:
      - coding-chain-rabbitmq
      - coding-chain-db
    image: coding-chain/api
    build:
      context: ../coding-chain-api
    restart: unless-stopped
    ports:
      - 5002:5002
    environment:
      ASPNETCORE_URLS: http://+:5002
      ASPNETCORE_ENVIRONMENT: Development
      DatabaseSettings:ConnectionString: "Server=coding-chain-db;Database=coding_chain;User Id=sa;Password=codingDevPwd21;"
      RabbitMqSettings:Host: "coding-chain-rabbitmq"
      RabbitMqSettings:Port: 5672
      RabbitMqSettings:Password: "guest"
      RabbitMqSettings:Username: "guest"
      CorsSettings:FrontEndUrl: "http://localhost:4200"
    networks:
      - coding-chain-network
  coding-chain-web:
    container_name: "coding-chain-web"
    image: coding-chain/web
    build:
      context: ../coding-chain-website
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: always
    environment:
      PORT: 80
    ports:
      - "4201:80"
    networks:
      - coding-chain-network

  coding-chain-worker:
    depends_on:
      - coding-chain-rabbitmq
    container_name: coding-chain-worker
    image: coding-chain/worker
    build:
      context: ../coding-chain-worker
    restart: unless-stopped
    ports:
      - 5004:5004
    environment:
      ASPNETCORE_URLS: http://+:5004
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMqSettings:Host: "coding-chain-rabbitmq"
      RabbitMqSettings:Port: 5672
      RabbitMqSettings:Password: "guest"
      RabbitMqSettings:Username: "guest"
      ElasticSearchSettings:Url: "http://coding-chain-elasticsearch:9200"
    volumes:
      -  ./coding-chain-worker/Templates:/home/app_user/Templates
    networks:
      - coding-chain-network

  ## APPLICATIONS ##

  coding-chain-db:
    container_name: coding-chain-db
    restart: unless-stopped
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=codingDevPwd21
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - ./database:/var/opt/mssql/data
    networks:
      - coding-chain-network
  coding-chain-rabbitmq:
    container_name: coding-chain-rabbitmq
    image: rabbitmq:3-management
    restart: unless-stopped
    hostname: coding-chain-rabbitmq
    volumes:
      - ./coding-chain-rabbitmq/conf:/etc/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - coding-chain-network

  coding-chain-elasticsearch:
    container_name: coding-chain-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    restart: unless-stopped
    environment:
      - node.name=coding-chain-elasticsearch
      - cluster.name=es-docker-cluster
      - cluster.routing.allocation.disk.threshold_enabled=false
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=coding-chain-elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./coding-chain-elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - coding-chain-network

  coding-chain-kibana:
    container_name: coding-chain-kibana
    image: docker.elastic.co/kibana/kibana:7.12.0
    restart: unless-stopped
    ports:
      - 5601:5601
    depends_on:
      - coding-chain-elasticsearch
    environment:
      ELASTICSEARCH_URL: http://coding-chain-elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://coding-chain-elasticsearch:9200"]'
    networks:
      - coding-chain-network
  coding-chain-redis:
    container_name: coding-chain-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./coding-chain-redis/conf/redis.conf:/redis.conf
    networks:
      - coding-chain-network
    command: [ "redis-server", "/redis.conf" ]

networks:
  coding-chain-network:
    driver: bridge
    name: coding-chain-network
