apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-chain-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coding-chain-api
  template:
    metadata:
      labels:
        app: coding-chain-api
    spec:
      containers:
      - name: coding-chain-api
        image: codingchain.azurecr.io/coding-chain-api:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        env:
        - name: DatabaseSettings__ConnectionString
          value: "Server=tcp:codingchain.database.windows.net,1433;Initial Catalog=coding-chain-db;Persist Security Info=False;User ID=CodingChain;Password=codingDevPwd21;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        - name: RedisCacheSettings__ConnectionString
          value: "coding-chain.redis.cache.windows.net:6380,password=cfovFM7qRo+825XX2YTXzWvHqrao47L7vflpXI0fthw=,ssl=True,abortConnect=False"
        volumeMounts:
          - name: azure
            mountPath: /app/AppData/Tournaments
      volumes:
        - name: azure
          azureFile:
            secretName: api-storage-secret
            shareName: api
            readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: coding-chain-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 443
    targetPort: 80
    protocol: TCP
  selector:
    app: coding-chain-api
